// Package k6 runs HTTP load tests with grafana/k6 ("k6" connector). The
// case's stages become constant-arrival-rate scenarios (open model: the
// arrival rate does not slow down when responses do, so there is no
// coordinated omission); the warm-up scenario is tagged phase=warmup and
// excluded from the measured metrics. Dropped iterations reveal a saturated
// load generator.
package k6

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/tuannm99/testkit/testkit/core/infra"
	"github.com/tuannm99/testkit/testkit/core/kit"
	"github.com/tuannm99/testkit/testkit/core/scenario"
)

type Connector struct {
	env *kit.Env
	d   *infra.Docker
}

func New() kit.Connector { return &Connector{d: infra.NewDocker(nil)} }

func (c *Connector) Name() string                                    { return "k6" }
func (c *Connector) Provision(_ context.Context, env *kit.Env) error { c.env = env; return nil }
func (c *Connector) Health(context.Context) error                    { return nil }
func (c *Connector) Collect(context.Context, kit.TimeWindow) ([]kit.Artifact, error) {
	return nil, nil
}
func (c *Connector) Teardown(context.Context) error { return nil }

// Entry builds the k6 entry script wrapping the user script with the
// open-model scenarios of the case.
func Entry(spec *scenario.PerfSpec) (string, time.Duration) {
	var b strings.Builder
	b.WriteString("// Generated by TestKit: open-model scenarios around the case script.\n")
	b.WriteString("import fn from './user.js';\n\nexport const options = {\n  discardResponseBodies: true,\n  scenarios: {\n")
	start := time.Duration(0)
	scen := func(name string, rate float64, d time.Duration, phase string) {
		r := int(math.Max(1, math.Round(rate)))
		vus := int(math.Max(10, float64(r)*2))
		fmt.Fprintf(&b, "    %s: { executor: 'constant-arrival-rate', rate: %d, timeUnit: '1s', duration: '%ds', startTime: '%ds', preAllocatedVUs: %d, maxVUs: %d, tags: { phase: '%s' } },\n",
			name, r, int(d.Seconds()), int(start.Seconds()), vus, vus*10, phase)
		start += d
	}
	if w := spec.WarmupDuration(); w > 0 {
		scen("warmup", spec.Stages[0].Rate, w, "warmup")
	}
	measured := time.Duration(0)
	for i, s := range spec.Stages {
		d, _ := time.ParseDuration(s.Duration)
		scen(fmt.Sprintf("stage%d", i+1), s.Rate, d, "measure")
		measured += d
	}
	b.WriteString("  },\n  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(50)', 'p(95)', 'p(99)'],\n")
	// Thresholds that always hold: they make k6 export the measured sub-metrics.
	b.WriteString("  thresholds: {\n    'http_req_duration{phase:measure}': ['max>=0'],\n    'http_req_failed{phase:measure}': ['rate>=0'],\n    'iterations{phase:measure}': ['count>=0'],\n    'dropped_iterations': ['count>=0'],\n  },\n};\n\nexport default fn;\n")
	return b.String(), measured
}

type summary struct {
	Metrics map[string]map[string]any `json:"metrics"`
}

// num reads a numeric field of a metric (k6 also stores threshold results there).
func (s summary) num(metric, field string) float64 {
	v, ok := s.Metrics[metric][field].(float64)
	if !ok {
		return 0
	}
	return v
}

// Apply runs k6.run {spec, rep, case_file, target, env}.
func (c *Connector) Apply(ctx context.Context, s kit.Step) (kit.Result, error) {
	if s.Name != "k6.run" {
		return kit.Result{}, fmt.Errorf("k6: unknown step %s", s.Name)
	}
	spec, _ := s.With["spec"].(*scenario.PerfSpec)
	rep := kit.Int(s.With, "rep", 1)
	target := kit.Str(s.With, "target")
	extra, _ := s.With["env"].(map[string]string)
	script := filepath.Join(filepath.Dir(kit.Str(s.With, "case_file")), spec.Script)
	user, err := os.ReadFile(script)
	if err != nil {
		return kit.Result{}, fmt.Errorf("k6 script: %w", err)
	}
	rel := path.Join(c.env.CaseDir, "perf", fmt.Sprintf("rep-%d", rep), "k6")
	dir := c.env.Evidence.Path(rel)
	if err := os.MkdirAll(dir, 0o777); err != nil {
		return kit.Result{}, err
	}
	_ = os.Chmod(dir, 0o777)
	entry, measured := Entry(spec)
	if err := os.WriteFile(filepath.Join(dir, "user.js"), user, 0o644); err != nil {
		return kit.Result{}, err
	}
	if err := os.WriteFile(filepath.Join(dir, "entry.js"), []byte(entry), 0o644); err != nil {
		return kit.Result{}, err
	}
	args := []string{"run", "--rm", "--network", c.env.Project.Network, "-v", dir + ":/scripts", "-w", "/scripts",
		"--user", fmt.Sprintf("%d:%d", os.Getuid(), os.Getgid()),
		"--label", infra.LabelManaged + "=true", "--label", infra.LabelProject + "=" + c.env.Project.Name,
		"--label", infra.LabelRunID + "=" + c.env.RunID, "--label", "testkit.ns=" + string(c.env.NS),
		"--label", infra.LabelService + "=k6", "-e", "TARGET=" + target, "-e", fmt.Sprintf("TESTKIT_REP=%d", rep),
		"-e", "TESTKIT_RUN_ID=" + c.env.RunID, "-e", "TESTKIT_NS=" + string(c.env.NS)}
	keys := make([]string, 0, len(extra))
	for k := range extra {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		args = append(args, "-e", k+"="+extra[k])
	}
	k6args := []string{"run", "--quiet", "--no-color", "--summary-export", "/scripts/summary.json",
		"--tag", "run_id=" + c.env.RunID, "--tag", "testkit_ns=" + string(c.env.NS)}
	if promUp(ctx, c.env.Runner.Prometheus) {
		args = append(args, "-e", "K6_PROMETHEUS_RW_SERVER_URL="+c.env.Internal.Prometheus+"/api/v1/write",
			"-e", "K6_PROMETHEUS_RW_TREND_STATS=p(50),p(95),p(99),max")
		k6args = append(k6args, "-o", "experimental-prometheus-rw")
	}
	args = append(args, c.env.Project.Get("K6_IMAGE"))
	args = append(args, k6args...)
	args = append(args, "/scripts/entry.js")
	out, runErr := c.d.Run(ctx, args...)
	if ce, ok := runErr.(*infra.CmdError); ok {
		out = ce.Stderr
	}
	_ = os.WriteFile(filepath.Join(dir, "k6.log"), []byte(out+"\n"), 0o644)
	arts := []kit.Artifact{{Kind: "log", Path: path.Join(rel, "k6.log"), Title: fmt.Sprintf("k6 output, repetition %d", rep), Source: "perf"}}
	raw, err := os.ReadFile(filepath.Join(dir, "summary.json"))
	if err != nil {
		return kit.Result{Artifacts: arts}, fmt.Errorf("k6 produced no summary (%v): %v", runErr, lastLines(out, 5))
	}
	arts = append(arts, kit.Artifact{Kind: "raw", Path: path.Join(rel, "summary.json"), Title: fmt.Sprintf("k6 summary, repetition %d", rep), Source: "perf"})
	var sm summary
	if err := json.Unmarshal(raw, &sm); err != nil {
		return kit.Result{Artifacts: arts}, err
	}
	const d, failed, it = "http_req_duration{phase:measure}", "http_req_failed{phase:measure}", "iterations{phase:measure}"
	m := map[string]float64{
		"p50_ms": sm.num(d, "p(50)"), "p95_ms": sm.num(d, "p(95)"), "p99_ms": sm.num(d, "p(99)"), "max_ms": sm.num(d, "max"),
		"error_rate": sm.num(failed, "value"), "jobs": sm.num(it, "count"), "throughput": sm.num(it, "count") / measured.Seconds(),
		"late": sm.num("dropped_iterations", "count"),
	}
	var offered float64
	for _, st := range spec.Stages {
		dd, _ := time.ParseDuration(st.Duration)
		offered += st.Rate * dd.Seconds()
	}
	m["offered_rate"] = offered / measured.Seconds()
	return kit.Result{Output: m, Artifacts: arts}, nil
}

func promUp(ctx context.Context, base string) bool {
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, base+"/-/ready", nil)
	resp, err := (&http.Client{Timeout: 2 * time.Second}).Do(req)
	if err != nil {
		return false
	}
	resp.Body.Close()
	return resp.StatusCode == 200
}

func lastLines(s string, n int) string {
	l := strings.Split(strings.TrimSpace(s), "\n")
	if len(l) > n {
		l = l[len(l)-n:]
	}
	return strings.Join(l, " | ")
}

var _ kit.Connector = (*Connector)(nil)
