package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/tuannm99/testkit/testkit/core/config"
	"github.com/tuannm99/testkit/testkit/core/conformance"
	"github.com/tuannm99/testkit/testkit/steps"
)

var (
	genStatusRe    = regexp.MustCompile(`(?m)^status:\s*draft\s*$`)
	genMarkerRe    = regexp.MustCompile(`(?m)^generated:.*by:\s*testkit gen`)
	genAdmissionRe = regexp.MustCompile(`(?m)^admission:`)
)

// newGenCmd generates the standard case pack of a service from its descriptor.
func newGenCmd(g *globals) *cobra.Command {
	var service, outDir string
	var patterns []string
	var check, list, prune bool
	cmd := &cobra.Command{
		Use:   "gen",
		Short: "Generate the standard case pack (duplicate delivery, poison message, crash, dependency fault, out of order, steady load) from the service descriptor",
		Long: `Reads the conformance section of testkit/services/<service>.yaml and writes draft cases
under <scenarios_dir>/generated/<service>/. The output is deterministic: the same descriptor gives
the same files. Files that are drafts carrying the "generated by testkit gen" marker are rewritten;
approved or hand-edited files are never touched (a difference is reported as drift).

  testkit gen --service order-worker          write / update the pack
  testkit gen --service order-worker --list   show what would be generated, and what is not applicable
  testkit gen --check                         exit 2 if any generated file is missing or out of date (CI)`,
		RunE: func(cmd *cobra.Command, args []string) error {
			out := cmd.OutOrStdout()
			p, err := config.LoadProject(g.root)
			if err != nil {
				return err
			}
			services, err := config.LoadServices(p.Abs(p.ServicesDir))
			if err != nil {
				return err
			}
			var names []string
			if service != "" {
				s, ok := services[service]
				if !ok {
					return exitErr{2, fmt.Sprintf("gen: unknown service %q", service)}
				}
				if s.Conformance == nil {
					return exitErr{2, fmt.Sprintf("gen: %s has no conformance section (see docs/bo-case-chuan.md)", service)}
				}
				names = []string{service}
			} else {
				for n, s := range services {
					if s.Conformance != nil {
						names = append(names, n)
					}
				}
				sort.Strings(names)
				if len(names) == 0 {
					return exitErr{2, "gen: no service declares a conformance section"}
				}
			}
			dir := outDir
			if dir == "" {
				dir = filepath.Join(p.Abs(p.ScenariosDir), "generated")
			} else if !filepath.IsAbs(dir) {
				dir = p.Abs(dir)
			}
			dirty := 0
			var written []string
			for _, n := range names {
				svc := services[n]
				rel, _ := filepath.Rel(p.Root, svc.File)
				plan, err := conformance.Generate(svc, conformance.Options{Patterns: patterns, Source: filepath.ToSlash(rel)})
				if err != nil {
					return exitErr{2, fmt.Sprintf("gen %s: %v", n, err)}
				}
				fmt.Fprintf(out, "%s: %d case(s)\n", n, len(plan.Files))
				want := map[string]bool{}
				for _, f := range plan.Files {
					path := filepath.Join(dir, f.Path)
					want[path] = true
					state, detail := genState(path, f.Body)
					fmt.Fprintf(out, "  %-9s %-34s %s\n", state, f.ID, f.Path)
					if detail != "" {
						fmt.Fprintf(out, "            %s\n", detail)
					}
					switch state {
					case "new", "updated":
						dirty++
						if !check && !list {
							if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
								return err
							}
							if err := os.WriteFile(path, f.Body, 0o644); err != nil {
								return err
							}
							written = append(written, path)
						}
					case "drift":
						dirty++
					}
				}
				for _, s := range plan.Skips {
					t := s.Trigger
					if t == "" {
						t = "-"
					}
					fmt.Fprintf(out, "  %-9s %-20s %-9s %s\n", "n/a", s.Pattern, t, s.Reason)
				}
				// Generated drafts of this service that the descriptor no longer produces.
				if len(patterns) == 0 {
					stale, _ := filepath.Glob(filepath.Join(dir, n, "*.yaml"))
					for _, f := range stale {
						if want[f] {
							continue
						}
						raw, _ := os.ReadFile(f)
						if genStatusRe.Match(raw) && genMarkerRe.Match(raw) && !genAdmissionRe.Match(raw) {
							fmt.Fprintf(out, "  %-9s %s (the descriptor no longer produces it)\n", "stale", filepath.Base(f))
							dirty++
							if prune && !check && !list {
								_ = os.Remove(f)
							}
						}
					}
				}
			}
			if len(written) > 0 {
				cs, err := loadCases(p, []string{dir})
				if err != nil {
					return exitErr{2, fmt.Sprintf("gen: the generated cases do not load: %v", err)}
				}
				if n := lintAll(out, cs, services, steps.Registry()); n > 0 {
					return exitErr{2, fmt.Sprintf("gen: %d lint error(s) in the generated cases (descriptor or generator bug)", n)}
				}
				fmt.Fprintf(out, "lint: %d case(s) OK. Next: testkit run --mutations %s   then   testkit admit %s\n", len(cs), dir, dir)
			}
			if check && dirty > 0 {
				return exitErr{2, fmt.Sprintf("gen --check: %d generated file(s) missing, out of date or stale; run `testkit gen`", dirty)}
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&service, "service", "", "service name (default: every service with a conformance section)")
	cmd.Flags().StringSliceVar(&patterns, "pattern", nil, "only these patterns: "+strings.Join(config.PatternNames, ", "))
	cmd.Flags().StringVar(&outDir, "out", "", "output directory (default <scenarios_dir>/generated)")
	cmd.Flags().BoolVar(&check, "check", false, "write nothing; exit 2 if a generated file is missing, out of date or stale")
	cmd.Flags().BoolVar(&list, "list", false, "write nothing; show the plan")
	cmd.Flags().BoolVar(&prune, "prune", false, "delete stale generated drafts")
	return cmd
}

// genState compares the file on disk with the generated body.
func genState(path string, body []byte) (state, detail string) {
	cur, err := os.ReadFile(path)
	if err != nil {
		return "new", ""
	}
	if bytes.Equal(cur, body) {
		return "unchanged", ""
	}
	switch {
	case genAdmissionRe.Match(cur) || !genStatusRe.Match(cur):
		return "drift", "approved: not touched. The descriptor now generates a different case; review the difference (testkit gen --out <tmp>) and re-admit if it matters"
	case !genMarkerRe.Match(cur):
		return "drift", "edited by hand (no generated marker): not touched"
	}
	return "updated", ""
}
